recipe:
  name: solubility_screening
  id: 1
  materials:
    liquids: { water }
    solids: { sodium_chloride }
  stations:
    InputStation:
      stationOp:
        pickup_batch:
          id: 1
          properties:
          output:
            name: "pick_rack_output"
            fields:
              success: bool
        place_batch:
          id: 2
          properties:
          output:
            name: "place_rack_output"
            fields:
              success: bool
    SolidDispensingQuantosQS2:
      stationOp:
        dispense_solid:
          id: 22
          properties:
            solid: sodium_chloride
            mass: 15
            unit: mg
          output:
            name: "solid_dispensing_output"
            fields:
              success: bool
              massDispensed: float
              startingVialMass: float
              unit: mg
    PeristalticLiquidDispensing:
      StationOp:
        dispense_liquid:
          id: 23
          properties:
            liquid: water
            volume: 2
            unit: mL
          output:
            name: "liquid_dispensing_output"
            fields:
              success: bool
              massDispensed: float
              unit: mg
              volDispensed: float
              unit: mL
    IkaPlateRCTDigital:
      StationOp:
        stirring:
          id: 24
          properties:
            rpm: 200
            duration: 1
            unit: seconds
          output:
            name: "ika_output"
            fields:
            success: bool
    SolubilityStation:
      StationOp:
        solubility_analysis:
          id: 25
          properties:
          output:
            name: "solubility"
            fields:
              success: bool
              solubility: float
  stationFlow:
    start:
      onSuccess: input_stn
      onFail: end
    input_stn:
      station: "InputStation"
      task: {"pickup_batch"}
      onSuccess: solid_disp
      onFail: end
    solid_disp:
      station: "SolidDispensingQuantosQS2"
      task: {"dispense_solid", sodium_chloride, 15, "mg"}
      onsuccess: liquid_disp
      onfail: end
    liquid_disp:
      station: "PeristalticLiquidDispensing"
      task: {"dispense_liquid", water, 2, "mL"}
      onSuccess: stir_stn
      onFail: end
    stir_stn:
      station: "IkaPlateRCTDigital"
      task: {"stirring", 200, 1, "seconds"}
      onSuccess: solubility_stn
      onFail: end
    solubility_stn:
      station: "SolubilityStation"
      task: {"solubility_analysis"}
      onSuccess: output_stn
      onFail: end
    output_stn:
      station: "InputStation"
      task: {"place_batch"}
      onSuccess: end
      onFail: end
    end:
