recipe:
  name: example_recipe
  id: 23
  batches:
    newBatch:
      id: 21
      name: new batch
  materials:
    liquids: { ethanol, methanol }
    solids: { sodium_chloride, benzimidiazole }
  stationOpDescriptors:
    {
      dispense_sodium,
      dispense_benzi,
      dispense_ethanol,
      dispense_methanol,
      stir_heat_chemicals,
      measure_crystal_growth
    }
  outcomeDescriptors:
    {
      quantos_dispense_outcome,
      liquid_dispense_outcome,
      ika_outcome,
      crystal_measurement,
    }
  stationFlow:
    1:
      station: "solid_dispensing_quantos_QS3"
      task: "dispense_sodium"
      onsuccess: 2
      onfail: 1
    2:
      station: "solid_dispensing_quantos_QS3"
      task: "dispense_benzi"
      onsuccess: 3
      onfail: 2
    3:
      station: "liquid_dispensing_peristaltic_pump_ardu"
      task: "dispense_ethanol"
      onsuccess: 4
      onfail: 3
    4:
      station: "liquid_dispensing_peristaltic_pump_ardu"
      task: "dispense_methanol"
      onsuccess: 5
      onfail: 4
    5:
      station: "ika_plate_rct_digital"
      task: "stir_heat_chemicals"
      onsuccess: 6
      onfail: 5
    6:
      station: "pxrd_analyser"
      task: "measure_crystal_growth"
      onsuccess: 0
      onfail: 1
