workflow:
  Robots:
    - type: PandaFranka
      id: 1
  Materials:
    liquids:
      - name: water
        amount_stored: 400
        unit: ml
        density: 997 #g/l
        pump_id: p1
        expiry_date: 2025-02-11
    solids:
      - name: sodium_chloride
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: cat1
        unit: mg
        expiry_date: 2025-02-11
  Stations:
    - type: IkaPlateDigital
      id: 2
      location:
        node_id: 1
        graph_id: 7
      process_state_machine:
        - type: StationLoadingSm
          args:
            batch_mode: true
            load_frame: '/ikaStation/loadFrame'
      parameters:
    - type: FisherWeightingStation
      id: 5
      location:
        node_id: 1
        graph_id: 7
      process_state_machine:
        - type: StationLoadingSm
          args:
            batch_mode: true
            load_frame: '/fisherScaleStation/loadFrame'
      parameters:
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
