workflow:
  Robots:
    PandaFranka:
      id: 1
  Materials:
    liquids:
      water:
        amount_stored: 400
        #kg/m3
        density: 997
        pump_id: 'p1'
        unit: ml
    solids:
      sodium_chloride:
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: 'cat1'
        unit: mg
  Stations:
    IkaPlateRCTDigital:
      id: 2
      location:
        node_id: 1
        graph_id: 7
      process_state_machine:
        StationLoadingSm:
          args:
            batch_mode: true
            load_frame: '/ikaStation/loadFrame'
      parameters:
    FisherWeightingStation:
      id: 5
      location:
        node_id: 1
        graph_id: 7
      process_state_machine:
        StationLoadingSm:
          args:
            batch_mode: true
            load_frame: '/fisherScaleStation/loadFrame'
      parameters:
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
