recipe:
  name: solubility_screening
  id: 1
  materials:
    liquids: { water }
    solids: { sodium_chloride }
  stations:
    InputStation:
      stationOp:
        InputStationPickupOp:
          id: 1
          properties:
          output:
            name: "InputStationResultDescriptor"
            fields:
              success: bool
        InputStationPlaceOp:
          id: 2
          properties:
          output:
            name: "InputStationResultDescriptor"
            fields:
              success: bool
    QuantosSolidDispenserQS2:
      stationOp:
        QuantosDispenseOpDescriptor:
          id: 22
          properties:
            solid: sodium_chloride
            mass: 5
            unit: mg
          output:
            name: "QuantosOutputDescriptor"
            fields:
              success: bool
              massDispensed: float
              startingVialMass: float
              unit: mg
    PeristalticLiquidDispensing:
      stationOp:
        PeristalticPumpOpDescriptor:
          id: 23
          properties:
            liquid: water
            volume: 2
            unit: mL
          output:
            name: "PeristalticPumpOutputDescriptor"
            fields:
              success: bool
              massDispensed: float
              unit: mg
              volDispensed: float
              unit: mL
    IkaPlateDigital:
      stationOp:
        IKAStirringOpDescriptor:
          id: 24
          properties:
            rpm: 200
            duration: 10
            unit: seconds
          output:
            name: "IKAOutputDescriptor"
            fields:
              success: bool
    SolubilityStation:
      stationOp:
        SolubilityOpDescriptor:
          id: 25
          properties:
            duration: 10
            unit: seconds
          output:
            name: "SolubilityDescriptor"
            fields:
              success: bool
              turbidity: float
  stationFlow:
    start:
      onSuccess: "solid_disp"
      onFail: "end"
    input_stn:
      station: "InputStation"
      task: "InputStationPickupOp"
      onSuccess: "solid_disp"
      onFail: "end"
    solid_disp:
      station: "QuantosSolidDispenserQS2"
      task: "QuantosDispenseOpDescriptor"
      onSuccess: "liquid_disp"
      onFail: "end"
    liquid_disp:
      station: "PeristalticLiquidDispensing"
      task: "PeristalticPumpOpDescriptor"
      onSuccess: "stir_stn"
      onFail: "end"
    stir_stn:
      station: "IkaPlateDigital"
      task: "IKAStirringOpDescriptor"
      onSuccess: "solubility_stn"
      onFail: "end"
    solubility_stn:
      station: "SolubilityStation"
      task: "SolubilityOpDescriptor"
      onSuccess: "end"
      onFail: "end"
    output_stn:
      station: "InputStation"
      task: "InputStationPlaceOp"
      onSuccess: "end"
      onFail: "end"
    end:
      ended: True
