# ============ Workflow Configuration ============
#
# general: this section describes the workflow general settings
#   name: the given workflow name
#   samples_per_batch: number of samples in a workflow batch
#   default_batch_input_location: default navigation graph location where a batch is added
#                                 where node_id stands for the node number in the navigation
#                                 graph whose id is given by graph_id
general:
  name: 
  samples_per_batch: 
  default_batch_input_location: 
    node_id:
    graph_id: 

# materials: this section describes the materials used in the workflow
#   liquids:
#     name: the liquid name
#     id: the liquid unique workflow id
#     amount: the liquid stored amount
#     unit: measurement unit representing stored amount, accepted units L, mL, uL,m3, cm3, mm3
#     density: liquid density
#     density_unit: measurement unit representing liquid density
#     details: all other liquid details such as its source, colour, etc. 
#     expiry_date: expiry date of the liquid
#   solids:
#     name: the solid name
#     id: the solid unique workflow id
#     amount: the solid stored amount
#     unit: the unit representing stored amount, accepted units g, mg, ug, kg
#     details: all other solid details such as its source, colour, etc.
#     expiry_date: expiry date of the solid
#
# for every solid and liquid used in the workflow, add a new entry and fill its fields as defined
materials:
  liquids:
    - name: 
      id: 
      amount: 
      unit: 
      density:
      density_unit: 
      details: 
      expiry_date: 
  solids:
    - name: 
      id: 
      amount: 
      unit: 
      details: 
      expiry_date:

# robots: this section describes the robots used in the workflow
#   type: the robot's class name as defined in archemist.robots.X.state 
#         note that X stands for the robot's given module found in archemist's robots 
#         module
#   id: the robot unique workflow id
#   batch_capacity: the number of batches the robot can carry/handle at a time
#   handler: robot handler class name as defined in archemist.robots.X.handler
#
# for every robot used in the workflow, add a new entry and fill its fields as defined
robots:
  - type:
    id: 
    batch_capacity:
    handler: 

# stations: this section describes the stations used in the workflow
#   type: the station's class name as defined in archemist.stations.X.state
#         note that X stands for the stations's given module found in archemist's 
#         stations module
#   id: the station unique workflow id
#   location: station's location in the robot navigation graph where node_id stands for the 
#             node number in the navigation graph whose id is given 
#   total_lot_capacity: number of lots the station can handle at a time
#   handler: station handler class name as defined in archemist.stations.X.handler
#   parameters: any additional parameters need to be passed to the station when initialized
#
# for every station used in the workflow, add a new entry and fill its fields as defined
stations:
  - type:
    id: 
    location: 
      node_id: 
      graph_id: 
    total_lot_capacity:
    handler: 
    parameters: 