general:
  name: apc_workflow
workflow_input:
  location:
    coordinates:
      - 1
      - 1
    descriptor: input_site
  samples_per_batch: 2
  batches_per_lot: 1
  total_lot_capacity: 1
  lot_input_process: null
workflow_output:
  location:
    coordinates:
      - 1
      - 1
    descriptor: output_site
  total_lot_capacity: 1
  lots_need_manual_removal: false
  lot_output_process: null
robots:
  - type: KMRIIWARobot
    id: 2
    handler: SimRobotOpHandler
    total_lot_capacity: 1
    onboard_capacity: 1
    
stations:
  - type: SyringePumpStation
    id: 1
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimSyringePumpStationHandler
    properties: null
    materials:
      liquids:
        - name: acetic_anhyride
          amount: 1000
          unit: mL
          density: 555
          density_unit: kg/m3
          details:
            inlet_port: 1
            outlet_port: 2
          expiry_date: 31/03/2024
        - name: water
          amount: 1000
          unit: mL
          density: 2000
          density_unit: kg/m3
          details:
            inlet_port: 3
            outlet_port: 4
          expiry_date: 31/03/2024
  - type: DiaphragmPumpStation
    id: 2
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimDiaphragmPumpStationHandler
    properties: null
    materials:
      liquids:
        - name: water
          amount: 5000
          unit: mL
          density: 1000
          density_unit: kg/m3
          details: null
          expiry_date: 31/03/2024
  - type: APCFumehoodStation
    id: 3
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimAPCFumehoodStationHandler
    properties:
      cartridges:
        - associated_solid: 4-aminophenol
          hotel_index: 1
    materials:
      solids:
        - name: 4-aminophenol
          amount: 30
          unit: g
          expiry_date: 31/03/2024
          details: null
  - type: MTSynthesisStation
    id: 4
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimMTSynthesisStationHandler
    materials: null
    properties:
      num_sampling_vials: 12
  - type: APCFiltrationStation
    id: 5
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimAPCFiltrationStationHandler
    materials: null
    properties: null
  - type: WatersLCMSStation
    id: 6
    location:
      coordinates:
        - 3
        - 1
      descriptor: lcms_station
    total_lot_capacity: 1
    handler: SimWatersLCMSStationHandler
    materials: null
    properties: null
  - type: APCWeighingStation
    id: 7
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimAPCWeighingStationHandler
    properties:
      funnel_storage_capacity: 3
    materials: null
  - type: APCMetaStation
    id: 8
    location:
      coordinates:
        - 1
        - 1
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimStationOpHandler
    materials: null
    properties: null
