workflow:
  Robots:
    KukaLBRIIWA:
      id: 1
    PandaFranka:
      id: 1
  Materials:
    liquids:
      water:
        amount_stored: 400
        density: 997 #kg/m3
        pump_id: 1
        unit: ml
    solids:
      sodium_chloride:
        amount_stored: 5000
        dispense_method: quantos
        cartridge_id: 1
        unit: mg
  Stations:
    input_station:
      id: 1
      location:
        graph_id: 7
        map_id: 2
        node_id: 7
        desk_pos: "quantos_rack"
    ika_plate_rct_digital:
      id: 2
      location:
        graph_id: 7
        map_id: 2
        node_id: 8
        desk_pos: "ika"
    liquid_dispensing_peristaltic_pump_ardu:
      id: 3
      location:
        graph_id: 7
        map_id: 2
        node_id: 8
        desk_pos: "pump"
      liquid_map:
        water: 1
      liquid_levels:
        water: {400, "ml"}
    solid_dispensing_quantos_QS2:
      id: 4
      location:
        graph_id: 7
        map_id: 2
        node_id: 7
        desk_pos: "quantos_back"
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
