workflow:
  Robots:
    KukaLBRIIWA:
      id: 1
    PandaFranka:
      id: 1
  Materials:
    liquids:
      water:
        amount_stored: 400
        #kg/m3
        density: 997
        pump_id: 'p1'
        unit: ml
    solids:
      sodium_chloride:
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: 'cat1'
        unit: mg
  Stations:
    InputStation:
      id: 1
      locations:
        rack_holder:
            graph_id: 7
            node_id: 8
            frame_name: "input_frame"
        pre_load_pos: 
        load_pos:
          graph_id: 7
          node_id: 7
          frame_name: "quantos_rack"
        post_load_pos: 
      parameters:
    IkaPlateRCTDigital:
      id: 2
      locations:
        rack_holder:
        pre_load_pos:
        load_pos:
          graph_id: 7
          node_id: 8
          frame_name: "ika"
        post_load_pos:
      parameters:
    PeristalticLiquidDispensing:
      id: 3
      locations:
        rack_holder:
        pre_load_pos:
          graph_id: 7
          node_id: 8
          frame_name: "handover_cube"
        load_pos:
          graph_id: 7
          node_id: 8
          frame_name: "pump"
        post_load_pos:
      parameters:
        liquid_pump_map:
          "water": "p1"
    QuantosSolidDispenserQS2:
      id: 4
      locations:
        rack_holder:
          graph_id: 7
          node_id: 7
          frame_name: 'quantos_rack'
        pre_load_pos:
        load_pos:
          graph_id: 7
          node_id: 7
          frame_name: "quantos_carousel"
        post_load_pos:
      parameters:
        catridges:
          cat1:
            solid: "sodium_chloride"
            remaining_dosages: 100
    SolubilityStation:
      id: 5
      locations:
        rack_holder:
        pre_load_pos:
        load_pos:
          graph_id: 7
          node_id: 8
          frame_name: "camera"
        post_load_pos:
          graph_id: 7
          node_id: 8
          frame_name: "handover_cube"
      parameters:
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
