workflow:
  Robots:
    KukaLBRIIWA:
      id: 1
    PandaFranka:
      id: 1
  Materials:
    liquids:
      water:
        amount_stored: 400
        #kg/m3
        density: 997
        pump_id: 'p1'
        unit: ml
    solids:
      sodium_chloride:
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: 'cat1'
        unit: mg
  Stations:
    InputStation:
      id: 1
      process_state_machine: SomeSM
      parameters:
    IkaPlateRCTDigital:
      id: 2
      process_state_machine: SomeSM
      parameters:
    PeristalticLiquidDispensing:
      id: 3
      process_state_machine: SomeSM
      parameters:
        liquid_pump_map:
          "water": "p1"
    QuantosSolidDispenserQS2:
      id: 4
      process_state_machine: SomeSM
      parameters:
        catridges:
          cat1:
            solid: "sodium_chloride"
            remaining_dosages: 100
    SolubilityStation:
      id: 5
      process_state_machine: SomeSM
      parameters:
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
