workflow:
  Robots:
    KukaLBRIIWA:
      id: 1
    PandaFranka:
      id: 1
  Materials:
    liquids:
      water:
        amount_stored: 400
        #kg/m3
        density: 997
        pump_id: 'p1'
        unit: ml
    solids:
      sodium_chloride:
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: 1
        unit: mg
  Stations:
    InputStation:
      id: 1
      location:
        graph_id: 7
        map_id: 2
        node_id: 7
        desk_pos: "quantos_rack"
    IkaPlateRCTDigital:
      id: 2
      location:
        graph_id: 7
        map_id: 2
        node_id: 8
        desk_pos: "ika"
    PeristalticLiquidDispensing:
      id: 3
      location:
        graph_id: 7
        map_id: 2
        node_id: 8
        desk_pos: "pump"
      liquid_map:
        p1: "water"
      liquid_levels:
        water: {amount: 400, unit: "ml"}
    QuantosSolidDispenserQS2:
      id: 4
      location:
        graph_id: 7
        map_id: 2
        node_id: 7
        desk_pos: "quantos_back"
  name: solubility_workflow
  timestamp: 08/26/2021, 15:28:26
