workflow_dir_path: 'C:\Users\hatem\m_algae_bot_workflow'
db_name: 'algae_bot_test'
batch_addition:
  location:
    node_id: 25
    graph_id: 1
    frame_name: '/InputStation'
  num_vials: 6
recipe_loop_mode: False
auto_batch_addition: False
